### ISSUE TITLE
Fejl i adressesøgning på androids

### ISSUE THREAD

**Issue by festersen1** [Septima/widget-issues#1]
Hvis man søger på en adresse fra en androidmobil, bliver der ikke zoomet ind. Hvis man i forvejen er zoomet ind, bliver man kun rykket lidt tættere på adressen. Det fungerer helt fint på iphones. Det er kun testet på Chrome, da det er er den eneste browser, der bliver anvendt af brugerne. 

Før adressesøgning: 
![image](https://user-images.githubusercontent.com/67626907/106580549-55671d00-6542-11eb-9bd4-bf8172895870.png)

Efter adressesøgning: 
![image](https://user-images.githubusercontent.com/67626907/106580598-6021b200-6542-11eb-87d3-59613088ce1d.png)

Til sammenligning ser det således ud på en iphone, efter søgning: 
![image](https://user-images.githubusercontent.com/67626907/106581043-b5f65a00-6542-11eb-98af-e592863b63b9.png)

**Comment by karstenpihl** [comment]
@festersen1 kan jeg få dig til at se om du har samme fejl på https://septima.dk/widget/examples/search1.html

**Comment by festersen1** [comment]
@karstenpihl Der sker det samme :)

**Comment by karstenpihl** [comment]
Tak for det. Jeg går videre med det og finder ud af hvad der er galt.

**Comment by karstenpihl** [comment]
Jeg kan også genskabe problemet i vores testmiljø. Vi finder ud af hvorfor problemet opstår og fikser det.

**Comment by karstenpihl** [comment]
Vi har fundet en løsning om kommer med en ny release meget snart.

**Comment by festersen1** [comment]
Perfekt! :)

**Comment by karstenpihl** [comment]
Version 2.21.19 er netop blevet released hvor dette problem skulle være løst. @festersen1 har du mulighed for at tjekke om det er nok?

**Comment by festersen1** [comment]
Det ser ikke ud som det virker.. og det burde være den nyeste version vi kører på: 
`<div data-widget-url="https://kortinfotest.hofor.dk/septima_widget_trial/Bygas/map_bygas_drift.json"></div>			
        <script src="https://widget.cdn.septima.dk/latest/widgetconfig.js"></script>`

**Comment by festersen1** [comment]
Det ser ikke ud som om det virker.. 
Og vi kører umiddelbart også på den nyeste version, vores "script" ser således ud: 
<div data-widget-url="https://kortinfotest.hofor.dk/septima_widget_trial/Bygas/map_bygas_drift.json"></div>			
        <script src="https://widget.cdn.septima.dk/latest/widgetconfig.js"></script>

**Comment by karstenpihl** [comment]
Jeg har testet på flere forskellige enheder hvor det virker. Kan det være fordi browseren har cached den gamle version?

Prøv evt. https://septima.dk/widget/examples/search1.html?a=1

**Comment by festersen1** [comment]
Det virker hverken på min telefon eller min kollegas...

**Comment by karstenpihl** [comment]
Det ser ud til at være en fejl i Android 10 og ældre versioner. Det er løst i Android 11. De telefoner jeg havde testet var alle opdateret. 

Kan du sige hvilken version af Android I har testet med?

Problemet skyldes at alle events i kortet afbrydes når tastaturet forsvinder på ældre versioner af Android.

Jeg må se om vi kan kompensere for denne fejl uden det gør det dårligere for de telefoner, der er opdateret.

**Comment by karstenpihl** [comment]
Det virker dog fint på en Samsung Galaxy S20, der kører Android 10.

**Comment by karstenpihl** [comment]
og OnePlus 8 med Android 10.

**Comment by karstenpihl** [comment]
Jeg ser hvad jeg kan gøre.

**Comment by festersen1** [comment]
Den ene telefon er en håbløs og gammel Sony, som nok kører på version 8 så det giver mening, hvis det ikke virker der. Min kollegas kører på version 10. 

Jeg er lidt udfordret ift. hjemmearbejde og udvalget af telefoner jeg kan teste på, men ser lige om jeg kan fange en anden kollega med en nyere version og se om det funker der :)

**Comment by festersen1** [comment]
@karstenpihl Det virker på alle de enheder, vi har testet på nu, så lukker issuet - tak for hjælpen :)
