### ISSUE TITLE
Default styling af nohit-message giver ikke så meget mening

### ISSUE THREAD

**Issue by cphflacour** [Septima/widget-issues#12]
Under conflict er nohit-message stylet som en notice med Ikon m.m.

Det giver ikke så meget mening. Dette kan jo ligeså godt være default som den normale template.

Jeg vil foreslå at stylingen fjernes - eventuelt at den erstattes af en nohit-template.

**Comment by karstenpihl** [comment]
Det synes jeg er en god idé. Jeg har lavet det så det kommer med i næste release.
