### ISSUE TITLE
Er der problemer med #dk_mat shortcut?

### ISSUE THREAD

**Issue by cphflacour** [Septima/widget-issues#13]
### Beskriv fejlen
WMS laget vises ikke for shortcut #dk_mat

Den genrerer følgende url:
https://services.kortforsyningen.dk/service?servicename=mat&token=f7ed24b5623301a90c1c6e60b30ca174&SERVICE=WMS&VERSION=1.1.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=TRUE&LAYERS=Jordstykke&STYLES=Sorte_Jordstykker&SRS=EPSG%3A25832&WIDTH=690&HEIGHT=551&BBOX=725418.5444785646%2C6176154.52909203%2C725991.8987701362%2C6176612.381577038

Den returnerer en HTTP 403: User not authorized

Prøv eventuelt her:
https://www.kk.dk/erhverv/ejendomme/almene-boliger/byggeri-af-nye-almene-boliger

**Comment by karstenpihl** [comment]
Det skyldes formentlig at Kortforsyningen er lukket. Det token vi har brugt kan tilsyneladende ikke bruges mere. I bruger Widget version 2.21.8. I version 2.25.0 skiftede vi til Datafordeleren/Dataforsyningen i stedet for Kortforsyningen. Så hvis I skifter til seneste version, vil det virke igen.
