### ISSUE TITLE
Problemer med adresse-autocomplete dropdown

### ISSUE THREAD

**Issue by cphflacour** [Septima/widget-issues#14]
Adressesøgning i selvstændig div.

Problemer med at vælge adresser fra dropdown. 

De øverste er OK, men når man når neden for widget-området kan man ikke vælge adressen.

Prøv for eksempel 
https://www.kk.dk/test-af-kort-linjes

Hvis man skriver rovsinggade - kan man vælge indtil nummer 25, men de øvrige numre kan ikke vælges.

**Comment by karstenpihl** [comment]
Det skyldes den CSS, der benyttes i løsningen. Mere præcist er det:
```css
.ssInput {
    width: 100% !important;
}
```
Jeg ved ikke hvorfor det er indsat, men det ser ud til at det giver problemer.
