### ISSUE TITLE
Kan jeg styre hvilke punkter der indgår i en routing

### ISSUE THREAD

**Issue by cphflacour** [Septima/widget-issues#15]
https://www.kk.dk/test-af-kort-linjes

Jeg har en Search og en Conflict der kigger på 4 lag. Jeg skal bruge Search resultatet og det første af Conflict resultaterne til en Routing.

Kan jeg styre det? Det virker som om Routing tager et vilkårligt Conflict resultat og bruger dette.

**Comment by karstenpihl** [comment]
Kombinationen af "conflict" med `"highlight": true` og "routing" fungerer ikke så godt. Så det er desværre ikke muligt pt. Hvis du sætter `"highlight": false`, så virker det.

Problemet skyldes at ingen af funktionerne kender noget til hinanden. Når en funktion tilføjer noget til kortet, så fyres et "featuresadded" event af. "routing" lytter på "featureadded" events og ved ikke hvem, der har aktiveret det.
