### ISSUE TITLE
CVR-søgninger med search-control fejler 

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/widget-issues#16]
### Beskriv fejlen
CVR-søgninger fejler.

### Hvilken funktion er fejlen relateret til?
search

### Hvordan kan vi genskabe fejlen
Kommer den med det samme, eller sker det når man:
1. Går til https://kort.solrod.dk/spatialmap?page=widget-local&name=kp21_byogbolig_kystnaerhedszone 
2. Klikker på Søg
3. Ser fejlen i js-konsollen

### Eventuel fejlbesked fra browseren
![image](https://user-images.githubusercontent.com/28621416/145992006-bfd8951e-bc9c-4c6e-9dc8-d60d808a1320.png)

**Comment by karstenpihl** [comment]
Du mangler et token for at kunne bruge servicen. Det sættes på med:
```json
{
    "type": "cvr",
    "options": {
        "searchindexToken": "...",
         "kommunekode": "269"
    }
}
```
Hvis du mangler dette token, kan du sende en mail.
