### ISSUE TITLE
Mulighed for at fjerne fremsøgt feature efter søgning

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/widget-issues#17]
Jeg ved ikke, om det er en fejl, eller om det er meningen, at når jeg trykker på krydset i søgefeltet (search control), fjernes kun teksten i søgefeltet. Jeg synes, det ville være logisk, hvis den fremsøgte feature i kortet også fjernes og forstørrelsesgalsset kommer tilbage i søgefeltet – så man ligesom kan starte på ny med sin søgning eller lave noget andet i kortet end at tekstsøge.
 
https://septima.dk/widget/examples/search1.html

**Comment by karstenpihl** [comment]
Det er noget, der er blevet efterspurgt i mange år. Lige pt. udstiller Septima Search ikke et event når der klikkes på krydset, men jeg rykker udvikleren 😃, og så kan det jo være det kommer inden så længe.

**Comment by karstenpihl** [comment]
Dette er løst i version 2.27.2
