### ISSUE TITLE
Option så Overlay lukker i stedet for minimeres

### ISSUE THREAD

**Issue by cphflacour** [Septima/widget-issues#18]
Det ville være fint hvis Overlay-funktionen havde en Option, så den forsvandt efter aktivering.

På vores kort på kk.dk - "støjer" hængelåsen lidt og brugssituationen med reaktivering af overlay, virker ikke naturlig.

**Comment by karstenpihl** [comment]
Det kan styres via CSS, så det er muligt i dag.

Men vi har tilføjet parameteren `onlyOnce`, der kommer med i næste release. Hvis den er sat til `true`, forsvinder hængelåsen og det vil ikke være muligt at låse kortet igen.
