### ISSUE TITLE
Chart.Js options delene - hrmm, svært at komme videre end bare jeres eksempler

### ISSUE THREAD

**Issue by jvalorehofor** [Septima/widget-issues#19]
Jeg er igang med at afprøve nogle af de mange mini BI graf aspekter, specielt bar/doughnut og jeg kan godt få jeres simple eksempler til at køre med egne data. Jeg har derimod store problemer med at forstå/få options delene til at virke, såvel scales (min/max, title på axis)

- https://www.chartjs.org/docs/latest/samples/scales/linear-min-max.html
- https://www.chartjs.org/docs/latest/samples/scale-options/titles.html

Er det muligt at få et hint eller at I f.eks. opdaterer nogle af eksemplerne med disse forhold ? 

Er det i øvrigt muligt at forestille sig/eksempler på at nogle har lavet en slags valg/checkbox, som så efterfølgende filtrerer lidt i data ? (Jeg kan finde eksempler på filtre på kort/liste, men ikke grafer) 

Pft. 
John Valore

**Comment by karstenpihl** [comment]
@jvalorehofor jeg vil prøve at lave et eksempel med en graf kombineret med et filter. 

Mht. de to eksempler, så skyldes det måske at vi ikke bruger version 3 af ChartJS. I stedet bruger vi version 2.9.4. Derfor skal du kigge på https://www.chartjs.org/docs/2.9.4/ hvor det nok vil give mere mening. Jeg sørger for at rette dokumentationen til.

Grunden til at vi bruger denne version, skyldes at konfigurationen ikke er bagudkompatibel og de eksisterende konfigurationer derfor ikke vil virke, hvis vi bare skifter til den nye version. Vi vil kigge på hvordan vi kan køre de to version sideløbende, så vi langsomt kan komme op på den nye version og få adgang til de nye muligheder.

**Comment by jvalorehofor** [comment]
Hej Karsten, 

Jeg er begyndt at kigge mod version 4 nu og der er noget smart der, som har irriteret os længe. Det med at når der er huller i data for nogle datasæt/tidsserier i en graf, så kan man vælge at der forlænges (spanGaps": true) eller få nogle lidt sjove start/slut på linjer eller bare punkter. 

Men der er et eksempel i v4, som handler om at man kan style en linie efter (gap/skippet) eller for den sags skyld en grafs udvikling på linjesegment niveau (stigende/faldende). https://www.chartjs.org/docs/latest/samples/line/segments.html

Jeg har prøvet at lege lidt med noget, men forstår nok ikke hvordan/hvor jeg skal gribe ind i et eksisterende septima json config miljø ift. det med at vurdere punkt0/punkt1 successivt 

Jeg er villig til at betale for et par timers indsats/hint i denne retning og kan også sende dig et foreløbig eksempel, som jeg ønsker at få introduceret sagerne på

**Comment by karstenpihl** [comment]
Eksemplet bruger en funktion til at style den stiplede linje. Men da konfigurationen i Widget kun er JSON, vil det ikke være muligt direkte. Dette kræver nok en ændring til Widget. Vi kan lave det så det er en template i stedet. Jeg bliver nødt til lige at prøve nogle ting af først. Kigger på det sidst på ugen.

**Comment by karstenpihl** [comment]
Med seneste version har jeg gjort det muligt at definere `segment` som en template i stil med:
```json
"segment": {
  "borderColor": "<%= ctx.p0.skip || ctx.p1.skip ? 'rgb(0,0,0,0.2)' : ctx.p0.parsed.y > ctx.p1.parsed.y ? 'rgb(192,75,75)' : undefined %>"
},
```
Som det er lige nu, understøtter det ikke at returnere arrays. 

Jeg har heller ikke testet ovenstående fuldt ud, da jeg ikke havde et godt eksempel. Hvis du har en widget konfiguration, der illustrere brugen og eventuelle problemer, så vil det være meget nemt for mig at teste af.

**Comment by karstenpihl** [comment]
Jeg lukker denne, da der ikke har været nogen aktivitet i lang tid.
