### ISSUE TITLE
Kan klikke info langt væk fra klikbare kortelementer

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/widget-issues#2]
### Beskriv fejlen
Alt klikbart i hvad der lader til at være alle vores Widgets har fået en stor buffer. Vi kan klikke info langt væk fra punkter og linjer (har ikke testet flader), som er klikbare. Det er over 200 px fra featuren.

### Hvilken funktion er fejlen relateret til?
info

### Hvordan kan vi genskabe fejlen
1. Gå til https://www.solrod.dk/borger/veje-og-trafik/sikker-trafik
2. Klikker info i kortet 200 px fra en markør i kortet
3. Ser fejlen ved at infoboksen åbner

Prøv evt. også:
https://www.solrod.dk/borger/veje-og-trafik/trafikindsatser
https://www.solrod.dk/kommunen/kontakt/raadhusets-placering

Vi kører med Widget til SpatialSuite 3.1.8. 
I testmiljøet har vi opgraderet til 3.2.1, men det løser ikke problemet.

**Comment by karstenpihl** [comment]
Jeg kan ikke genskabe problemet. Jeg har testet i Chrome, Safari og IE11. 

Skifter cursoren også 200px fra featuren?

**Comment by jdgsolrod** [comment]
Hmm. Det er i Chrome. Og ja cusoren skifter også (se skærmbillede). 

Har testet i explorer, Edge, Firefox, og også i Chrome på en fjerncomputer. Det virker fint de steder. Så det er kun i Chrome på min PC. Har forsøg at rydde browser cache og genstarte Chrome.

![image](https://user-images.githubusercontent.com/28621416/109785402-64f28800-7c0c-11eb-977c-ef7380ff55d8.png)

**Comment by karstenpihl** [comment]
Meget mærkeligt. Hvilken version af Chrome har du. Jeg tester lige i Chrome på nogle flere maskiner.

**Comment by jdgsolrod** [comment]
I det jeg tjekkede version startede opdatering. Efter opdatering og genstart af Chrome er fejlen væk. Irriterende Chrome ikke opdaterede automatisk. Beklager ulejligheden.

**Comment by jdgsolrod** [comment]
Hej. Jeg har haft dette problem igen, selv efter jeg har opgraderet til seneste Chrome-version. Jeg har fundet frem til, at min duckduckgo-udvidelse til Chrome har en påvirkning. Hvis jeg deaktiverer udvidelsen forsvinder problemet.
