### ISSUE TITLE
De ydre widget DIVs bliver forsynet med en title=

### ISSUE THREAD

**Issue by cphflacour** [Septima/widget-issues#20]
For bedre at understøtte skærmlæsere m.m. har vores webteam anmodet om at de ydre DIVs forsynes med en forklarende title-attribut.

Det kunne for eksempel være: 

`<div data-widget-detach="s5keuu-Search" class="widget-detached widget-contains-search" title="Adressesøgning">`

eller 

`<div data-widget="s5keuu" data-widget-initialized="true" class="widget-skin-default widget-container widget-contains-map widget-inactivemap" title="Interaktivt kort">`

**Comment by karstenpihl** [comment]
Husk at under normale omstændigheder vil I selv kunne tilføje de titler, som du efterspørger, da det er dig, der som udgangspunkt indsætter dem på jeres hjemmeside. 

Lige præcist hos jer, er det måske lidt bøvlet fordi I ikke altid selv har adgang til HTML'en i jeres CMS, men jeg tror faktisk I kan.

Men med den seneste version 2.36.6 er det nu muligt at tilføje `title` til `map` og en række andre funktioner i JSON konfigurationen. Når dette gøres, vil der blive tilføjet en title på elementet som beskrevet. Se https://septima.dk/widget/documentation.html for yderligere info.
