### ISSUE TITLE
Cache af bagvedliggende json - hvor sker det henne/tips til at bremse dette

### ISSUE THREAD

**Issue by jvalorehofor** [Septima/widget-issues#21]
Hej, 
Vi oplever jo at vi kan lave en fin widget og under udvikling kan vi køre en browser i incognito/udvikler - cache disablet tilstand og ændringer slår så umiddelbart igennem. 

Når vi så er færdige/deployer, så oplever vi at det ikke er de seneste json/ændringer, som slår igennem - og det tolker jeg som at der et eller andet sted er en cache af den bagvedliggende json - uden at jeg helt kan pege på om det er hos jer/ISP/os - men er det et trick/tips til at undgå dette cache aspekt (enten server side og/eller client side) . Det virker nemlig som om at nogle mobilers browser/cache agerer anderledes end andre desktop browsere (Ctrl-F5 vinklen)  

Prøvede at læse lidt på håndtag som : https://www.sitepoint.com/solve-caching-conundrums/ - men blev ikke helt klog på sagerne. Men sikker på at andre har været der før mig, fundet håndtagene. 

På forhånd tak 

Vh
John Valore

**Comment by karstenpihl** [comment]
Hvis I har konfigurationen liggende i en JSON fil på jeres webserver, så kan denne webserver være sat op til at cache kraftigt, hvilket jo er godt i langt de fleste tilfælde. Men når der sker ændringer, så er det selvfølgelig et problem. Hvis I selv har styr over webserveren, så er jeg helt sikker på at det kan styres dér.

Hvis I ikke har kontrol over webserveren, så er første skridt er at tjekke om JSON filen kommer rigtig ud. Åben derfor JSON filen i browseren som f.eks.: 

https://septima.dk/widget/config/overlay.json 

og se om den indeholder ændringerne. Herefter prøv at tilføje en ekstra parameter som her:

https://septima.dk/widget/config/overlay.json?_=27

Hvis det giver den opdaterede JSON og ikke den cachede, så kan I styre det ved at tilføje den ekstra parameter dér hvor HTML'en er sat ind. Det kunne være noget i stil med:
```html
<div data-widget-url="https://septima.dk/widget/config/overlay.json?_=27"></div>
```

Alternativt må I placere jeres JSON filer et sted, der er bedre til at styre cachen. Vi har https://widgetadmin.septima.dk hvor I kan få admin og placere jeres konfigurationer. Her sørger vi for at cache og invalidere cachen når der sker ændringer.

**Comment by jvalorehofor** [comment]
Hej, 
Prøvede flere forskellige håndtag til at styre min IIS cache, https://blog.krusen.dk/disable-browser-caching-specific-files-folders , men jeg synes ikke at det virkede set fra Chromes udvikler værktøj, som hele tiden meldt om "disk cache". 

Jeg prøvede så din lille fleksible snyde tilgang og det virkede meget konsekvent, i ihvertilfald set fra Chrome af. Nu prøver jeg så i næste uge på lidt flere devices. 

Tusind tak for hjælpen foreløbig.
