### ISSUE TITLE
Skraveret fyldmønster vises ikke når stilart hentes fra fil

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/widget-issues#3]
### Beskriv fejlen
Skraveret fyldmønster vises ikke når stilart hentes fra fil.
Derudover er det ærgerligt at skraveringen ikke er med i signaturforklaringen.

### Hvilken funktion er fejlen relateret til?
features_style.fillpattern

### Hvordan kan vi genskabe fejlen
Kommer den med det samme, eller sker det når man:
1. Indsæt features_style (eksempel herunder) for polygon feature direkte i widget-konfigurations-json-filen herunder og se at skraveringen vises i en Widget
2. Skriv den separat i en json-fil og inkludér den fra widget-konfigurations-json-filen (a la "features_style": "../data/styles/test.json")
3. Se at skraveringen ikke vises

### Hvordan ser konfigurationen ud?
```json
{
  "strokecolor": "rgba(188,20,19,1)",
  "strokewidth": 2,
  "fillcolor": "rgba(188,20,19,0.2)",
  "fillpattern": {
    "pattern": "hatch",
    "fillcolor": "rgba(188,20,19,0.2)",
    "strokecolor": "rgba(188,20,19,0.8)",
    "offset": 0,
    "size": 1,
    "spacing": 5,
    "angle": 60,
    "scale": 2
  },
  "strokecolor_selected": "rgba(0,0,0,0.5)",
  "strokewidth_selected": 4,
  "fillpattern_selected": {
    "pattern": "hatch",
    "fillcolor": "rgba(188,20,19,0.2)",
    "strokecolor": "rgba(188,20,19,0.8)",
    "offset": 0,
    "size": 1,
    "spacing": 5,
    "angle": 60,
    "scale": 2
  }
}
```

### Eventuel fejlbesked fra browseren
Der er ingen fejlbeskeder

### Widget hvor skraveret stilart er inkluderet fra fil
![image](https://user-images.githubusercontent.com/28621416/112329806-cc55a200-8cb7-11eb-9edf-4e180d0ceb6e.png)

### Widget hvor skraveret stilart er skrevet direkte i konfigurationsfil
![image](https://user-images.githubusercontent.com/28621416/112329825-d081bf80-8cb7-11eb-8099-f2b532f1ec58.png)

**Comment by karstenpihl** [comment]
Vi har ikke reklameret så meget for skraveringen endnu netop fordi der er et par ting, der ikke er helt optimale. Herunder at den ikke vises i signaturforklaringen. Vi har også oplevet at den ikke virker i IE11, så vær lige opmærksom på det. 

At skraveringen ikke virker når den hentes fra en fil, kan jeg ikke forstå. Det vil jeg lige undersøge. 

Hvilken version af Septima Widget bruger du?

**Comment by jdgsolrod** [comment]
Vi bruger SpS Widget v3.2.2. Og vi bruger ikke IE. Det er i Chrome, jeg oplever problemet.

**Comment by karstenpihl** [comment]
Du kan løse det ved at tilføje `"fillpattern": true` til laget som det er gjort her:

```json
      {
        "features": true,
        "features_host": "https://geoserver.plandata.dk/geoserver/wfs?service=WFS&typeName=pdk:theme_pdk_lokalplan_vedtaget_v&request=GetFeature&version=1.0.0&maxfeatures=1000&outputFormat=json&CQL_FILTER=anvgen=31 AND komnr=340",
        "features_dataType": "json",
        "fillpattern": true,
        "features_style": "../data/styles/fillpattern.json",
        "type": "geojson"
      }
```
Vi opdaterer dokumentationen.

**Comment by karstenpihl** [comment]
Dokumentation er nu opdateret
