### ISSUE TITLE
search med mulighed for at tildele className

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/widget-issues#4]
Mange controls har mulighed for at tildele className for optimeret CSS-styling men ikke search. Er der en god grund til det? Det vil vi kunne bruge.

**Comment by karstenpihl** [comment]
Du har ret. Det er rettet nu og kommer med i næste release.

**Comment by jdgsolrod** [comment]
Jeg har opgraderet Widget til Spatial Suite til 3.2.6, og jeg får ikke className på search. Min search er detached.

**Comment by karstenpihl** [comment]
Det kommer med hos mig:

![image](https://user-images.githubusercontent.com/3703683/145954862-2ef0565d-4dbc-4a3a-85c3-251a86e84801.png)

med: 
```json
        "search":{
          "disable":false,
          "detach": "search",
          "className": "CUSTOM_CLASS_NAME",
          "keepInFullscreen": true,
          "displaytext":"Søg1",
          "features_style":{
            "namedstyle": "#004"
          },
          "driver":[
            {
              "type": "dawa",
              "options": {
                "kommunekode": "153"
              }
            }
          ],
          "minResolution":3.2
        }
```

Er der et sted hvor jeg kan se dit eksempel?

**Comment by jdgsolrod** [comment]
Det var en brain fart sent i går eftermiddag. Jeg fik sat klassen på layerswitch.
