### ISSUE TITLE
Forslag: Drop detach for signaturforklaring i fuldskærmsvisning

### ISSUE THREAD

**Issue by jdgsolrod** [Septima/widget-issues#5]
### Beskriv hvad du ønsker ændret
Hvis en Widget har detached signaturforklaring, gøres den ikke detached i fuldskærmsvisning (gerne styret med en parameter). Det er typisk, fordi der ikke er plads i kortet, at signaturforklaringer detaches, men netop plads bliver der, når man går i fuldskærmsvisning (måske lige med undtagelse af visning på en iPhone5 eller SE eller lign. lille smartphoneskærm).

Der kan være placeret andet, som f.eks. scaleline i nedre venstre hjørne af kortet. Jeg foreslå signaturforklaringen overtager pladsen (widget-control-position-ll), da den er vigtigere for at kunne læse kortet.

### Er det noget du vil være med til at financiere?
Muligvis.

**Comment by karstenpihl** [comment]
Jeg synes det er en god idé og der har tidligere været ønske om det samme for listevisningen. 

Der er to dele der skal løses:
1. Håndtering af det event, der sker når kortet går i fullscreen og tilbage. Dette skal alle funktioner holde øje med og gøre det nødvendige for at få en form for fixed position.
2. Stylingen kan være meget individuel og det er derfor ikke altid vi bare kan løsrive det "detached" element. Men vi kan tage udgangspunkt i den default style, der følger med.

Jeg vil foreslå at vi starter med "layerswitch" (jeg går ud fra at det er den du bruger til signaturforklaringe) og udvider det til andre funktioner efter behov. Det vil tage 4-6 timer for punkt 1 og 2 på "layerswitch" og tage udgangspunkt i default stylingen. Custom styling skal evt. tilpasses efterfølgende. Det vil være noget man aktivt vælger til, så den er bagudkompatibel.

**Comment by karstenpihl** [comment]
Så har vi implementeret denne mulighed for udvalgte funktioner, bl.a. Lagvælger, Find nærmeste, Rute, Google Street View og Mapillay. Det kommer med i næste release af Septima Widget sammen med en masse andre forbedringer.

Tak til Solrød Kommune for at financiere denne udvikling, der vil være tilgængelig for alle, der bruger Septima Widget.

For at være bagudkompatibel, er det noget, der skal aktiveres på de "detached" funktioner, man ønsker at have med i fullscreen visningen. Det gøres ved at tilføje `"keepInFullscreen": true` til konfigurationen af funktionen.

Vi lukker dette issue når den nye version er tilgængelig.

**Comment by karstenpihl** [comment]
Så er version 2.25.0 klar med de muligheder.
