### ISSUE TITLE
Authentication til widgets

### ISSUE THREAD

**Issue by festersen1** [Septima/widget-issues#6]
Vi skal til at anvende widgets til internt brug, og vil derfor gerne undersøge muligheden for at få opsat authentication, så det kun er dedikerede brugere, der kan tilgå - gerne med windows authentication. 

Er det muligt? 

Vi vil gerne være med til at financiere det :)

**Comment by festersen1** [comment]
Vi har fundet en anden løsning, så det er ikke længere aktuelt.

**Comment by karstenpihl** [comment]
Det er muligt at hente data, der ligger bag f.eks. en Basic authentication via Septima Widget. Men det er sjældent optimalt, da brugernavn/password kommer til at stå i klar tekst i konfigurationen. Derfor vil man typisk starte med at beskytte den side, som Septima Widget vises på. Det er den måde som vi oftes ser Septima Widget anvendt.

Hvis der er brug for yderligere muligheder, så sig til. Så finder vi en løsning.
