### ISSUE TITLE
Print af kort virker ikke med WMS'er 

### ISSUE THREAD

**Issue by festersen1** [Septima/widget-issues#7]
### Beskriv fejlen
Printfunktionen virker ikke, når der er tilknyttet WMS'er i opsætningen. Det fungerer fint med WFS'er og andre services. 
Når man klikker på print kører funktionen bare i ring: 
![image](https://user-images.githubusercontent.com/67626907/117813011-d7ae5e00-b262-11eb-8e01-1b6dcfecd2b9.png)

### Hvordan ser konfigurationen ud?
https://kortinfotest.hofor.dk/septima_widget_trial/test/printtest.html 
Json: 
https://kortinfotest.hofor.dk/septima_widget_trial/test/printtest.json

**Comment by karstenpihl** [comment]
Prøv at tilføje `"crossOrigin": "anonymous"` til WMS laget:

```json
{
  "name": "V2",
  "id": "DKJORD_V2",
  "crossOrigin": "anonymous",
  "type": "WMS",
  "selectable": false,
  "host": "https://arealinformation.miljoeportal.dk/gis/services/DKJord/MapServer/WMSServer?",
  "layer_name": "DKJORD_V2",
  "format": "image/png",
  "singleTile": false,
  "legendConfig": {
    "icon": "hofor_v2.png"
  },
  "visible": true
},
```

**Comment by festersen1** [comment]
Smukt, det virker - tak! :)
