### ISSUE TITLE
Jeg kan ikke få ignore til at fungere, sådan at vi kan bruge fallback på vores baggrundskort

### ISSUE THREAD

**Issue by rsp-solrod** [Septima/widget-issues#8]
### Beskriv fejlen
Selvom jeg sætter ignore på det ene ud af to lag med baggrundskort, bliver det stadig vist i widgetten.

### Hvilken funktion er fejlen relateret til?
Det er ignore, der ikke har nogen effekt.

### Hvordan kan vi genskabe fejlen
Kommer den med det samme, eller sker det når man:
Går ind på widgetten, og ser at det grå baggrundskort bliver tegnet. Jeg har ikke publiceret en widget med fallback på, fordi jeg ikke kan få det til at virke. Men jeg sætter json ind.

### Hvordan ser konfigurationen ud?
```json
{"objects": [{ "id":"kp21_retningslinjekort_for_landbrugsomraade", 
  "map": {
    "height": "450px",
    "crs": "25832",
    "maxZoomLevel": 0,
    "minZoomLevel": 13,
    "css": ["https://kort.solrod.dk/css/custom/customwidget.css","https://kort.solrod.dk/css/custom/customwidget_kp21.css"],
    "view":{
      "name":"solroed_kommune",
      "zoomLevel":6.7,
      "x":700324,
      "y":6159203
    },
    "mapcontrols": {
      "scaleline": true
    },
    "layer": [
      {
        "name": "grundkort",
        "namedlayer": "#dk_graa", 
        "id": "theme-dtk_skaermkort_graa_daf",
        "ignore": true,
        "legendConfig": { 
          "icon": "https://kort.solrod.dk/modules/widget/images/daempet.png" 
        }
      },
      {
        "name": "Luftfoto",
        "namedlayer": "#dk_luftfoto",
        "id": "orto",
        "fallback": "theme-dtk_skaermkort_graa_daf",
        "legendConfig": { 
          "icon": "https://kort.solrod.dk/modules/widget/images/ortofoto.png" 
        },
        "transition": true,
        "visible": false
      },
      {
        "name":"Særligt værdifuldt landbrugsområde",
        "type":"WMS",
        "host":"https://kort.solrod.dk/wms?SERVICENAME=kommuneplan21",
        "layer_name":"theme-kp21_vaerdifuldt_landbrugsomraade",
        "id": "theme-kp21_vaerdifuldt_landbrugsomraade",
        "singleTile":true,
        "copyright": "Solrød Kommune",
        "legendConfig": {
          "type": "sps",
          "host": "https://kort.solrod.dk",
          "profile": "kommuneplan21"
        }
      },
      {
        "name":"Kommunegrænse",
        "type":"WMS",
        "host":"https://kort.solrod.dk/wms?SERVICENAME=kommuneplan21",
        "layer_name":"theme-kommunegrense_land_sort",
        "id": "theme-kommunegrense_land_sort",
        "singleTile":true,
        "legendConfig": {
          "type": "sps",
          "host": "https://kort.solrod.dk",
          "profile": "kommuneplan21"
        }
      },
      {
        "name":"Forvaltning2 husnumre",
        "type":"WMS",
        "host":"https://kort.solrod.dk/wms?SERVICENAME=kommuneplan21",
        "layer_name":"theme_forvaltning2_husnummer",
        "id": "theme_forvaltning2_husnummer",
        "singleTile":true
      }
    ],
    "controls": [
      {
        "search": {
          "disable": false,
          "detach": "kp21_kp21_retningslinjekort_for_landbrugsomraade_search",
          "charLimit": 3,
          "displaytext": "Søg efter en adresse",
          "features_style": {
            "fillopacity": 1,
            "fillcolor": "rgba(255,0,0,0.3)",
            "strokewidth": 1,
            "strokecolor": "rgba(0,0,200,0.5)",
            "symbol": "circle",
            "radius": 7.5
          },
          "driver": [
            {
              "type": "dawa",
              "options": {
                "kommunekode": "269"
              }
            },
            {
              "type": "geosearch",
              "options": {
                "kommunekode": "269",
                "targets": ["matrikelnumre"]
              }
            }
          ]
        },
        "info": {
          "disable": false,
          "eventtype": "click",
          "type": "cloud",
          "multifeature": 2
        },
        "layerswitch": {
          "disable": false,
          "detach": "kp21_retningslinjekort_for_landbrugsomraade_layerswitch",
          "layerOrder": true,
          "layers": [
            "theme-kp21_vaerdifuldt_landbrugsomraade"
          ],
          "showbuttons": true,
          "showlegend": true,
          "groups": [
            {
              "title": "Signaturforklaring",
              "layers": [
                "theme-kp21_vaerdifuldt_landbrugsomraade"
              ]
            }
          ]
        },
        "layertoggle": {
          "disable": true,
          "className": "widget-control-position-ur",
          "layers": [
            "dk_graa",
            "orto"
          ]
        },
        "fullscreen": {
          "disable": false
        }
      }
    ]
  }
}]}
```

### Eventuel fejlbesked fra browseren
Der kommer ingen fejlbeskeder.

**Comment by karstenpihl** [comment]
Bemærk at muligheden for fallback kom med i version 2.23.0. Så du skal sikre at du minimum benytter den version. Det ser ud til at I bruger version 2.22.7. I bruger Widget modulet til Spatial Suite og I kan derfor nemt skifte til en nyere version ved at opdatere versionnummeret direkte i deploy.xml i widget modulet.

Se også et eksempel her: https://septima.dk/widget/examples/layer8.html (selvom der ikke er meget at se).

I dit tilfælde har du i øvrigt sat "Luftfoto" til `"visible": false` hvilket gør at "Luftfoto" ikke vises. Hvis du sætter den til `true` så vil laget "grundkort" blive vist hvis "Luftfoto" fejler. Din konfiguration virker fint hos mig, hvis du gør det.

Et fallback lag er et ekstra lag, der kun skal vises hvis hvis et andet lag fejler. Derfor tilføjes "ignore" på det lag. Jeg vil anbefale at man bruger et fallback lag fra en anden tjeneste end det lag, der kan fejl. Så begge lag bør ikke hentes fra f.eks. Datafordeleren, da der så er stor sandsynlighed for at begge lag fejler.

**Comment by rsp-solrod** [comment]
Ah, ok.. Jeg tjekkede versionsnummeret på Spatial Suite-modulet, og så at det var nyeste. Jeg var ikke klar over, at vi kunne opdatere widget-versionen i deployfilen. Men nu kører det fint med ignoren – så det ser ud til at fugnere :-) Tak for hjælpen!

Selve lagene i mit eksempel var kun til test – det er ikke meningen, at skærmkort og luftfoto skal være fallback for hinanden.

Venlig hilsen
Rasmus Slot
GIS-medarbejder
***@***.***D76698.E6371270]
Teknik og Miljø
Solrød Center 1
2680 Solrød Strand
Telefon +4556182000
www.solrod.dk<http://www.solrod.dk>
***@***.***D76698.E6371270]


Fra: Karsten Pihl ***@***.***>
Sendt: 21. juni 2021 12:24
Til: Septima/widget-issues ***@***.***>
Cc: Rasmus Slot ***@***.***>; Author ***@***.***>
Emne: Re: [Septima/widget-issues] Jeg kan ikke få ignore til at fungere, sådan at vi kan bruge fallback på vores baggrundskort (#8)


Bemærk at muligheden for fallback kom med i version 2.23.0. Så du skal sikre at du minimum benytter den version. Det ser ud til at I bruger version 2.22.7. I bruger Widget modulet til Spatial Suite og I kan derfor nemt skifte til en nyere version ved at opdatere versionnummeret direkte i deploy.xml i widget modulet.

Se også et eksempel her: https://septima.dk/widget/examples/layer8.html (selvom der ikke er meget at se).

I dit tilfælde har du i øvrigt sat "Luftfoto" til "visible": false hvilket gør at "Luftfoto" ikke vises. Hvis du sætter den til true så vil laget "grundkort" blive vist hvis "Luftfoto" fejler. Din konfiguration virker fint hos mig, hvis du gør det.

Et fallback lag er et ekstra lag, der kun skal vises hvis hvis et andet lag fejler. Derfor tilføjes "ignore" på det lag. Jeg vil anbefale at man bruger et fallback lag fra en anden tjeneste end det lag, der kan fejl. Så begge lag bør ikke hentes fra f.eks. Datafordeleren, da der så er stor sandsynlighed for at begge lag fejler.
